name: Check pull request

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
jobs:
  check_and_merge_pr:
    if: ${{ github.repository == 'aaron-binary/check-and-merge-pr' }}
    runs-on: ubuntu-latest
    steps:
      - name: Use local check pull request action
        uses: ./.github/actions/check-pull-request
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
