name: Create teams

on:
  workflow_dispatch:
jobs:
  check_approvals:
    runs-on: ubuntu-latest
    steps:
      # We require a checkout so we can read the "people" folder.
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use local create teams action
        uses: ./.github/actions/create-teams
        with:
          team_size: 5
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
